apiVersion: apps/v1
kind: Deployment
metadata:
  name: love-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: love-calculator
  template:
    metadata:
      labels:
        app: love-calculator
    spec:
      containers:
      - name: love-calculator
        image: chimaiberi1990/love-calculator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
                                                                          